name: ecometer_manual_balancer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+1  # or 1.0.3+3, just higher than before



environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2

  # You can move this to dev_dependencies later if you like
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ecometer_logo.png
