name: ecometer_manual_balancer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # âœ… keep shared_preferences
  shared_preferences: ^2.2.2

  # This can stay here or be moved to dev_dependencies later
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ecometer_logo.png
