name: ecometer_manual_balancer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # ✅ Firebase for auth & app init
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0

  # ✅ Local settings
  shared_preferences: ^2.2.2

  # Lints (can stay here or in dev_dependencies)
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ecometer_logo.png
